name: Pipeline examen frabarser1
on:
  push:
  workflow_dispatch: #en pestaña de actions va a salir un boton para correr el pipeline manualmente
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' #Versión con la que haya creado el proyecto
      - name: Contruir y Ejecutar los test
        run: |
          chmod +x gradlew 
          ./gradlew build
  Mail:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Enviar correo
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "Ejecucion correcta."
          body: "Se ha ejecutado correctamente."
          to: ${{ secrets.DESTINATARIO }}
          from: ${{ github.actor }}